variable "asg_name" {}
variable "asg_size_min" {}
variable "asg_size_max" {}
variable "asg_size_desired" {}
variable "external_dns_name" {}
variable "internal_dns_name" {}
variable "load_balancers" {}
variable "clouddriver_polling" {}
variable "instance_type" {}
variable "associate_public_ip_address" {}
variable "default_sg_id" {}
variable "key_name" {}
variable "s3_bucket" {}
variable "s3_prefix" {}
variable "subnet_ids" {}
variable "default_aws_region" {}
variable "instance_profile" {}

variable "redis_primary_endpoint_address" {}
variable "local_redis" {}